### ISSUE TITLE
auto-corrections/suggestions on the misspelled words by users

### ISSUE THREAD

**Issue by catssifi** [catssifi/Catssificator#12]
Write a function or a class that will correct any misspelled inputs (preferably from the past knowledge in the system if not then do the dictionary look-ups)

Define the distance of the misspelled and intended word, x.  The len(x) should be not more than 2.  
I.e. a) If user types 'beleve', it should be corrected to 'believe' 
      b) if user types 'beliee', it should also be corrected to 'believe'
      c) if user types 'bliee', then no match is found

Also, the first letter must be matched any intended word.  With that said, 'celieve' will not be matched to 'believe' since their first letter does match even the rest of their words are matched

Note: 
1) It needs to be integrate with the cache system so to reduce the server loads

**Comment by wwken** [comment]
It has been implemented and released on Jan 30
